# General Jekyll Config
name: Good Product Management
description: Good Product Management from Scott Colfer.
url: "https://goodproduct.management/"

# Build settings
markdown: kramdown
theme: minima
