# General Jekyll Config
name: Good Product Management
description: Products that improve lives by Scott Colfer.
url: "https://goodproduct.management/"

# Build settings
markdown: kramdown
theme: minima
